### PR TITLE
Add callback onNoIntentActivitiesFound to SpClient.

### PR DESCRIPTION
**Pull request by jschamburger**
When using Sourcepoint on TV, I was missing a callback which informs the app that no activities were able to open a URL. This did exist in earlier versions of Sourcepoint, but was not present in the current release.

Since some TV devices do not have a browser, clicking on URLs in the Sourcepoint dialogs did not trigger any action. By informing the client app, it's at least possible to display a dialog telling the user that the link could not be opened.

### CODE REVIEW

**Comment by carmelo-iriti** [comment]
Hi @jschamburger, 

thank you for the message. 

Could you please discuss your needs with our Account Manager so we can optimally channel your request?

**Comment by jschamburger** [comment]
Hi @carmelo-iriti,
I have already discussed this with Sebastian Rinas; he encouraged me to open a pull request :)

**Comment by carmelo-iriti** [comment]
sure, let me sync with Sebastian in a way to organise the work 👍🏻

**Comment by carmelo-iriti** [comment]
Hi @jschamburger , 
I have seen the changes, can you help me understand what triggers the onNoIntentActivitiesFound?

**Comment by carmelo-iriti** [comment]
I'm going to close this mr, create a different branch and create a new mr 👍🏻

**Comment by jschamburger** [comment]
Alright. I'm not sure why this needs to be a separate MR, but I'm happy that this feature will make it into an upcoming release.

**Comment by carmelo-iriti** [comment]
Hi @jschamburger , we just released the 6.3.4 version containing the fix you requested, it'll be available in a couple of hours  👍🏻

**Pull request closed without merging**
